
package com.mycompany.tsp;


public enum CitiesEnum {
    KRAKOW, WARSZAWA, WROCLAW, GDANSK, BYDGOSZCZ, POZNAN, KATOWICE, BIALYSTOK, 
    LODZ, SANDOMIERZ, KAZIMIERZ_DOLNY, RESZEL, MIELNO, KARPACZ, OLKUSZ,
    KRYNICA_ZDROJ, HEL, ZAMOSC, ZAKOPANE, SZCZECIN
}
